export const HOME_GET_INITIAL_DATA_BEGIN = 'HOME_GET_INITIAL_DATA_BEGIN';
export const HOME_GET_INITIAL_DATA_SUCCESS = 'HOME_GET_INITIAL_DATA_SUCCESS';
export const HOME_GET_INITIAL_DATA_FAILURE = 'HOME_GET_INITIAL_DATA_FAILURE';
export const HOME_GET_INITIAL_DATA_DISMISS_ERROR = 'HOME_GET_INITIAL_DATA_DISMISS_ERROR';
export const HOME_REGISTER_USER = 'HOME_REGISTER_USER';
