# Generated by Django 3.0.5 on 2020-05-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='variantes',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='date_creation',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
        migrations.AddField(
            model_name='exercicevariant',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kine.Exercice'),
        ),
        migrations.AddField(
            model_name='exercicevariant',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kine.Media'),
        ),
    ]
