# Generated by Django 3.0.5 on 2020-04-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercice',
            options={'verbose_name': 'Exercice', 'verbose_name_plural': 'Exercices'},
        ),
        migrations.AlterModelOptions(
            name='exerciceroutine',
            options={'verbose_name': 'Exercice Routine', 'verbose_name_plural': 'Exercice Routines'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patient'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AddField(
            model_name='exercice',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kine.Media'),
        ),
    ]
