# Generated by Django 3.0.5 on 2020-04-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0002_auto_20200418_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
