# Generated by Django 3.0.5 on 2020-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0003_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('Video', 'Video'), ('Photo', 'Photo')], default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('Traitement', 'Video'), ('Post-Traitement', 'Photo')], default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciceroutine',
            name='rep',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Repetitions'),
        ),
        migrations.AlterField(
            model_name='exerciceroutine',
            name='serie',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Series'),
        ),
    ]
