# Generated by Django 3.0.5 on 2020-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0006_auto_20200418_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
