# Generated by Django 3.0.5 on 2020-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0007_auto_20200419_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, to='kine.Program'),
        ),
    ]
